### PR TITLE
adds compose and pipe all

### PR DESCRIPTION
**Pull request by stoeffel**
Any thoughts on this? I think it's nice to have compose/pipe and *All.

### CODE REVIEW

**Comment by stoeffel** [comment]
... or should we have just compose/pipeAll? hmmm... I think since its just 1 line of code it's okay to have both :laughing:

**Comment by tomekwi** [comment]
> since its just 1 line of code

:D

I think we can do away with only `composeAll` and `pipeAll` – and name them `compose` and `pipe`. You can always do `const compose2 = shave(2, compose)` with our *swiss* army knife :)

**Comment by stoeffel** [comment]
> You can always do const compose2 = shave(2, compose) with our swiss army knife :)

Yop, thought so too. I'm afk at the moment. I will refactor it as soon as possible.

**Comment by stoeffel** [comment]
@tomekwi @hemanth should we go with this? The downside is you have to use `shave` if you want it to work with `reduce`.

**Comment by hemanth** [comment]
That would be a pain!

**Comment by tomekwi** [comment]
For me `compose(f, g, h, i)` is more readable than `[f, g, h, i].reduce(compose)`. But as you wish – we can have both just as well.

Or even leave `composeAll` out and say that all our functions have a definite number of arguments. That woudln’t be bad – AFAIK it’s common in pure languages.

**Comment by stoeffel** [comment]
Let's keep it simple for now.

**Pull request closed without merging**
