### PR TITLE
Rename `curry2` to `curry`

### PR DESCRIPTION
**Pull request by tomekwi**
I have the feeling that `curry2` would be used 90% of times. How about renaming this to `curry`? @stoeffel @hemanth?

### CODE REVIEW

**Comment by tomekwi** [comment]
Keep in mind that `curry1` is being busted out.

**Comment by hemanth** [comment]
I would still vote for `curry2` because it's more explicit.

**Comment by stoeffel** [comment]
> because it's more explicit.

Curry sounds too much like a auto curry function.
You can still do `var curry = require ('1-liners/module/curry2');`.

**Comment by tomekwi** [comment]
:+1: closing this then

**Pull request closed without merging**
