### PR TITLE
`isTruthy` and `isFalsy`

### PR DESCRIPTION
**Pull request by tomekwi**
How about these?

### isTruthy

Same as `!!`.

```js
var isTruthy = require('1-liners/isTruthy');

isTruthy('yes');  // => true
isTruthy(true);   // => true
isTruthy([]);     // => true

isTruthy('');     // => false
isTruthy(0);      // => false
isTruthy(false);  // => false
```

### isFalsy

Same as `!`.

```js
var isFalsy = require('1-liners/isFalsy');

isFalsy('yes');  // => false
isFalsy(true);   // => false
isFalsy([]);     // => false

isFalsy('');     // => true
isFalsy(0);      // => true
isFalsy(false);  // => true
```

### CODE REVIEW

**Comment by stoeffel** [comment]
:+1: nice

**Comment by stoeffel** [comment]
needs a rebase

**Comment by tomekwi** [comment]
Yes sir!

**Comment by stoeffel** [comment]
Merged manually
d1c12fb08fee17ee253a1ef63ae1fe86b02f05dd
50f920366b727e5ddb8ec89a39630195ab20b8cd
3bd99e07440d837535d3d73f4e39a04c6f265e6b
:+1:

**Pull request closed without merging**
