### PR TITLE
add npm task to create module/index.js

### LINKED ISSUE #32: A way to pull in the whole lot
When size doesn’t matter, you’d sometimes just want to save 5 lines of code and write:

```js
import {flip, curry2, split, and, or, isTruthy} from '1-liners/module';
```

Here’s one way to do it – which works both for `require` and the ES6 `import`:
- [`module.js`](https://github.com/tomekwi/virtual-dom-lite/blob/0bc3/module.js)
- [`module/index.js`](https://github.com/tomekwi/virtual-dom-lite/blob/0bc3/module/index.js)

### PR DESCRIPTION
**Pull request by stoeffel**
closes #32

### CODE REVIEW

**Comment by stoeffel** [comment]
haha I accidentally squashed one commit from @tomekwi now git thinks you did this :)

**Comment by stoeffel** [comment]
hmm should we change the index in the root folder to be es5 or should we compile it too?

**Comment by stoeffel** [comment]
@tomekwi @hemanth input?

**Comment by tomekwi** [comment]
Looks delicious! :ice_cream:

**Pull request merged**
