### PR TITLE
Pick

### PR DESCRIPTION
**Pull request by tomekwi**
@stoeffel @hemanth any thoughts?

### CODE REVIEW

**Comment by stoeffel** [comment]
:+1: nice

**Comment by tomekwi** [comment]
:rocket:

**Comment by stoeffel** [comment]
The opposite of this function would be nice too. To drop some attributes. i.e. `drop(['password', 'hash'], user);`

**Comment by tomekwi** [comment]
:+1: I’ll add this as an issue so it doesn’t get lost

**Comment by stoeffel** [comment]
:+1:

**Comment by hemanth** [comment]
:+1:

**Pull request merged**
