### PR TITLE
adds takeWhile

### PR DESCRIPTION
**Pull request by stoeffel**
How do you like this guys?
To complicated?

//cc @hemanth @tomekwi

### CODE REVIEW

**Comment by stoeffel** [comment]
If you guys like it we could also add takeUntil, dropWhile and dropUntil

**Comment by hemanth** [comment]
:+1: we need this for fp-js as well :p

**Comment by tomekwi** [comment]
How is this different from *filter*?

**Comment by stoeffel** [comment]
It stops when it finds a match. checkout https://lodash.com/docs#takeWhile f.e.

**Comment by tomekwi** [comment]
Good one! :)

**Pull request merged**
