### PR TITLE
Replace `.npmignore` with `files`

### PR DESCRIPTION
**Pull request by tomekwi**
In my view it’s better to explicitly opt in for what we need. And when someone downloads a package he doesn’t need jsHint config and other crap.

I also need the ES6 module stuff directly in ES6 projects.

### CODE REVIEW

**Comment by tomekwi** [comment]
I’d also vote to rename `src` to module. This way you can

```js
import flip from '1-liners/module/flip';
```

It just looks nice and not hackish, that’s all.

**Comment by tomekwi** [comment]
And a [`/module.js` like this one](https://github.com/tomekwi/node-raw/blob/697d/module.js) will allow:

```js
import oneLiners from '1-liners/module';
```

Modify it slightly, and we can get this as well:

```js
import {join, flip, curry} from '1-liners/module';
```

– if we want such a thing.

**Comment by hemanth** [comment]
:+1:

**Comment by stoeffel** [comment]
:+1: will you rename src?

**Pull request merged**
