### PR TITLE
Make `curry`ies more flexible

### PR DESCRIPTION
**Pull request by tomekwi**
Here’s one to show what I mean. Useful?

### CODE REVIEW

**Comment by stoeffel** [comment]
:+1: This is sweet!

**Comment by tomekwi** [comment]
Then let me do the rest. Just a moment.

**Comment by stoeffel** [comment]
No hurry :smile: Thanks

**Comment by stoeffel** [comment]
hmm.. but you can do some strange stuff with this
try : `equal(curry2(f)(1, 2)(2, 3), 3);`
and I would expect `equal(curry2(f)(1, 2), 3);` this to work.

**Comment by tomekwi** [comment]
> try : equal(curry2(f)(1, 2)(2, 3), 3);

That’s right. But it’s just like with any other function. `Number(3, 'a', true) === 3`.

> I would expect equal(curry2(f)(1, 2), 3); this to work.

`curry1` → `f()`   
`curry2` → `f()()`   
`curry3` → `f()()()`   
`curry4` → `f()()()()`

That’s how I see it.

**Comment by tomekwi** [comment]
The problem is with `curry1` – because your `parseInt` example would no longer work with `(f) => (...args) => f(...args)`.

And that makes no sense anyway as it’s the same as `f => f`.

**Comment by stoeffel** [comment]
Yes, I think you are right. How about we add a function to create a new function which only takes a specified amount of args?

`takes(1, parseInt)` creates a new function that oly passes 1arg to parseInt.

**Comment by stoeffel** [comment]
If we add something like `takes`(it should have a better name) we should remove curry1 or change it to work like the other curries.

**Comment by tomekwi** [comment]
> add a function to create a new function which only takes a specified amount of args

> remove curry1

Definitely good ideas :) In my view `curry1` was a little ambiguous.

> it should have a better name

How about `trim`?

**Comment by stoeffel** [comment]
`trim` sounds like `String.prototype.trim`, but how about `trimArgs`?

**Comment by tomekwi** [comment]
- `clip`?
- `chop`?
- `crop`?

Tell me if I’m just being too creative here :)

**Comment by tomekwi** [comment]
- `snip`?

**Comment by tomekwi** [comment]
`limit`?

**Comment by tomekwi** [comment]
> There are only two hard things in Computer Science: cache invalidation and naming things.
>
> — Phil Karlton

**Comment by stoeffel** [comment]
:smiley: I like `clip`

**Comment by tomekwi** [comment]
- `shave`?

**Comment by tomekwi** [comment]
I’d cast my vote on [`snip`](http://www.oxforddictionaries.com/us/definition/english/snip) and [`shave`](http://www.oxforddictionaries.com/us/definition/english/shave).

[`clip`](http://www.oxforddictionaries.com/us/definition/english/clip) seems to have more than one meaning – and now I think about it, it resembles *clipboard* – and makes the impression of fastening something somewhere. Don’t you think?

**Comment by stoeffel** [comment]
Yop you are right.

**Pull request merged**
