### PR TITLE
moving docs to code

### LINKED ISSUE #53: Moving documentation to jsdoc
```
/**
 * @module and
 * 
 * Same as `a && b`.
 *
 * @example
 *   var and = require('1-liners/and');
 * 
 *   and(true, true); // => true
 *   and(false, true); // => false
 */
export default (x, y) => x && y;
```

### PR DESCRIPTION
**Pull request by stoeffel**
This will move all documentation to the code except for the curry and uncurry functions, since they will be removed. 

closes #53

### CODE REVIEW

**Comment by stoeffel** [comment]
Is this good to go? input? We should merge this before we add to many new functions.

**Comment by stoeffel** [comment]
I will remove the unnecessary * anyway. Thanks for pointing me to dox looks nice.

**Comment by stoeffel** [comment]
btw dox outputs this for i.e. `and`

```json
[
  {
    "tags": [
      {
        "type": "module",
        "string": "1-liners/and \nSame as `a && b`.\n",
        "html": "<p>1-liners/and<br />Same as <code>a &amp;&amp; b</code>.</p>"
      },
      {
        "type": "example",
        "string": "\n\tvar and = require('1-liners/and');\n\n\tand(true, true); // => true\n\tand(false, true); // => false",
        "html": "<pre><code>var and = require(&#39;1-liners/and&#39;);\n\nand(true, true); // =&gt; true\nand(false, true); // =&gt; false\n</code></pre>"
      }
    ],
    "description": {
      "full": "",
      "summary": "",
      "body": ""
    },
    "isPrivate": false,
    "isConstructor": false,
    "isClass": false,
    "isEvent": false,
    "ignore": false,
    "line": 1,
    "codeStart": 14,
    "code": "export default (x, y) => x && y;",
    "ctx": false
  }
]
```

This could be used for #54

**Comment by stoeffel** [comment]
:checkered_flag:

**Comment by hemanth** [comment]
:+1:

**Pull request merged**
